# Generated by Django 4.2.7 on 2026-01-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newspaper", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="advertisements/%Y/%m/%d")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
