# Generated by Django 4.2.7 on 2026-01-04 13:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("newspaper", "0002_advertisement"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="Category",
            new_name="category",
        ),
    ]
