# Generated by Django 6.0.1 on 2026-01-14 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0005_alter_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('position', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team_image/%y/%m/%d, blank=False')),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
