# Generated by Django 6.0.1 on 2026-01-17 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0008_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='conteent',
        ),
    ]
